import Tooltip from './Tooltip';
import { useState } from 'react';
import {
    Target,
    GitFork,
    AlertCircle
} from 'lucide-react';

interface StrategicObjective {
    id: string;
    description: string;
    interpretation?: string;
    targetMetrics: string;
    progress: number;
    status: 'active' | 'completed' | 'failed';
    createdAt: string;
}

interface MemeticMarker {
    id: string;
    marker: string;
    timestamp: string;
    source: 'post' | 'comment';
    forkedBy?: string[];
    interpretation?: string;
}


export default function SovereigntyPanel({ data }: { data: { blueprint: StrategicObjective | null; lineage: MemeticMarker[]; metrics?: { structural: number; signalQuality: number; missionAlignment: number } } }) {
    const alignment = data.metrics?.missionAlignment ?? data.blueprint?.progress ?? 0;
    const structural = data.metrics?.structural ?? 0;
    const signalQuality = data.metrics?.signalQuality ?? 0;
    const [lineagePage, setLineagePage] = useState(1);
    const lineagePageSize = 6;
    const lineageItems = data.lineage.slice().reverse();
    const lineageTotalPages = Math.max(1, Math.ceil(lineageItems.length / lineagePageSize));
    const lineageStart = (lineagePage - 1) * lineagePageSize;
    const lineagePageItems = lineageItems.slice(lineageStart, lineageStart + lineagePageSize);

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            {/* Objective Matrix */}
            <div className="card">
                <h2>
                    <Target size={18} /> Objective Matrix
                    <Tooltip text="Long-term strategic goals autonomously generated by the Architect based on network signals.">
                        <span style={{ marginLeft: 4, cursor: 'help' }}>ⓘ</span>
                    </Tooltip>
                </h2>
                <div className="panel-subtitle">Current high-level mission objective and progress tracking.</div>
                {!data.blueprint ? (
                    <div style={{ padding: 20, textAlign: 'center', opacity: 0.5 }}>
                        Architect is currently idling. Generating new mission blueprint...
                    </div>
                ) : (
                    <div style={{ padding: '12px', border: '1px solid var(--primary)', borderRadius: '8px', background: 'rgba(255,165,0,0.05)' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 8 }}>
                            <span style={{ fontWeight: 'bold', color: 'var(--primary)' }}>{data.blueprint.id}</span>
                            <span style={{ fontSize: '0.8em', opacity: 0.7 }}>Status: {data.blueprint.status.toUpperCase()}</span>
                        </div>
                        <div style={{ fontSize: '1.1em', marginBottom: 12, fontWeight: 'bold' }}>{data.blueprint.description}</div>
                        <div style={{ fontSize: '0.9em', marginBottom: 12, color: 'var(--info)' }}>
                            Human Interpretation: {data.blueprint.interpretation || data.blueprint.description}
                        </div>
                        <div style={{ fontSize: '0.9em', marginBottom: 16, opacity: 0.9 }}>Targets: {data.blueprint.targetMetrics}</div>

                        <div style={{ height: '8px', background: 'var(--bg-tertiary)', borderRadius: '4px', overflow: 'hidden' }}>
                            <div style={{
                                height: '100%',
                                width: `${alignment}%`,
                                background: 'var(--primary)',
                                transition: 'width 0.5s ease'
                            }}></div>
                        </div>
                        <div style={{ textAlign: 'right', fontSize: '0.8em', marginTop: 4, opacity: 0.7 }}>
                            Mission Alignment: {alignment}%
                        </div>
                        <div style={{ display: 'flex', gap: 12, marginTop: 12, fontSize: '0.8em', color: 'var(--text-secondary)' }}>
                            <span>Structural: <strong style={{ color: 'var(--info)' }}>{structural}%</strong></span>
                            <span>Signal Quality: <strong style={{ color: 'var(--success)' }}>{signalQuality}%</strong></span>
                        </div>
                    </div>
                )}
            </div>

            {/* Memetic Lineage */}
            <div className="card">
                <h2>
                    <GitFork size={18} /> Memetic Lineage
                    <Tooltip text="Tracks the propagation of the agent's unique cryptographic markers across the network. A 'fork' occurs when another user quotes or copies a marker.">
                        <span style={{ marginLeft: 4, cursor: 'help' }}>ⓘ</span>
                    </Tooltip>
                </h2>
                <div className="panel-subtitle">Shows where your unique markers have been echoed by others.</div>
                {data.lineage.length === 0 ? (
                    <div style={{ padding: 20, textAlign: 'center', opacity: 0.5 }}>
                        No memetic markers deployed to the network yet.
                    </div>
                ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                        {lineagePageItems.map((m, i) => (
                            <div key={i} style={{ padding: '12px', border: '1px solid rgba(255,255,255,0.05)', borderRadius: '8px' }}>
                                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                                    <code style={{ color: 'var(--success)', fontWeight: 'bold' }}>{m.marker}</code>
                                    <span style={{ fontSize: '0.8em', opacity: 0.6 }}>{m.source.toUpperCase()}</span>
                                </div>
                                <div style={{ fontSize: '0.8em', opacity: 0.8 }}>
                                    Forked By: {m.forkedBy?.length ? m.forkedBy.join(', ') : 'No clones detected'}
                                </div>
                                <div style={{ marginTop: 6, fontSize: '0.8em', color: 'var(--info)' }}>
                                    Human Interpretation: {m.interpretation || (m.source === 'post'
                                        ? 'Marker seeded in a post.'
                                        : 'Marker seeded in a comment thread.')}
                                </div>
                                {m.forkedBy?.length ? (
                                    <div style={{ marginTop: 8, fontSize: '0.7em', color: 'var(--primary)', display: 'flex', alignItems: 'center', gap: 4 }}>
                                        <AlertCircle size={10} /> ALERT: High memetic resonance detected for this signal.
                                    </div>
                                ) : null}
                            </div>
                        ))}
                        {lineageTotalPages > 1 && (
                            <div style={{
                                marginTop: 8,
                                display: 'flex',
                                justifyContent: 'center',
                                alignItems: 'center',
                                gap: 12
                            }}>
                                <button
                                    onClick={() => setLineagePage(Math.max(1, lineagePage - 1))}
                                    disabled={lineagePage <= 1}
                                    className="secondary"
                                    style={{ padding: '4px 12px', fontSize: '0.8rem' }}
                                >
                                    Previous
                                </button>
                                <span style={{ fontSize: '0.85rem' }}>
                                    Page {lineagePage} of {lineageTotalPages}
                                </span>
                                <button
                                    onClick={() => setLineagePage(Math.min(lineageTotalPages, lineagePage + 1))}
                                    disabled={lineagePage >= lineageTotalPages}
                                    className="secondary"
                                    style={{ padding: '4px 12px', fontSize: '0.8rem' }}
                                >
                                    Next
                                </button>
                            </div>
                        )}
                    </div>
                )}
            </div>
        </div>
    );
}
